version: "2.4"

services:
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=fiap-fastfood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/fiap-fastfood
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - API_PAYMENT_URL=http://localhost:8082/api
    command: postgres
    ports:
      - "5432:5432"
      
      
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"  
    links:
     - postgres