version: '1'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fiap-fastfood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  backend:
    image: guilhermemunhoz/app:latest
    ports:
      - "80:80"

volumes:
  db_data:
    driver: local
