apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
spec:
  storageClassName: databases
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/wsl/data/postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-postgres
spec:
  storageClassName: databases
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      