apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-food-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-food-api
      name: fiap-food-api
    spec:
      containers:
        - name: fiap-food-api-container
          image: updateconsultoria/fiap-food:v2.0
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: secret-fiap-food-api
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m
  replicas: 2
  selector:
    matchLabels:
      app: fiap-food-api