# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/fiap-fastfood
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      API_PAYMENT_URL: http://localhost:8082

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build-DB
      run: docker-compose build      

    - name: Create-DB
      run: docker-compose up -d

    - name: Sonar Scan
      run: mvn clean verify Dspring.profiles.active=deploy --file pom.xml sonar:sonar -Dsonar.projectKey=kenzleyDev_fiap-food-api -Dsonar.organization=kenzleydev
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Build with Maven
      run: mvn -B package -Dspring.profiles.active=deploy --file pom.xml

    #- name: SonarCloud Scan
     # uses: SonarSource/sonarcloud-github-action@master
      #env:
       # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
      # Artifact name
        name: api em Java
      # A file, directory or wildcard pattern that describes what to upload
        path: main
          

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

